### ISSUE TITLE
Crash with 2 PKs & duplicate dim name

### ISSUE THREAD

**Issue by LookerTimG** [llooker/pylookml#12]
Traceback (most recent call last):
  File "/Users/timgoldstein/working/tools_lookml/tool1_lookml.py", line 20, in <module>
    myFile = proj.file('order_items.view.lkml')
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 400, in file
    return File(self.gitControllerSession.absoluteOutputPath + '/' + path)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 632, in __init__
    self.vws = self.view_collection(self.json_data['views'])
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 497, in __init__
    self.add(view)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 507, in add
    v = View(v)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 891, in __init__
    super(View, self).__init__(input)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 773, in __init__
    self._bind_lkml(input)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 924, in _bind_lkml
    self + Dimension(field)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 982, in __add__
    return self.addField(other)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 1205, in addField
    self.setPrimaryKey(field.identifier)
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 1261, in setPrimaryKey
    self.unSetPrimaryKey()
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 1307, in unSetPrimaryKey
    pk.unSetPrimaryKey()
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 2139, in unSetPrimaryKey
    self.unSetProperty('primary_key')
  File "/usr/local/lib/python3.7/site-packages/lookml/lookml.py", line 829, in unSetProperty
    self.properties.__del__(name)
AttributeError: 'Properties' object has no attribute '__del__'

**Comment by russlooker** [comment]
fixed in latest release
