### ISSUE TITLE
Not able to create a file from view

### ISSUE THREAD

**Issue by subbaraocherukuri** [llooker/pylookml#66]
>>> view_name = lookml.View('test_n')
>>> lookml.File(view_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "I:\ds\tools\python3.8\3.8.10\lib\site-packages\lookml\lib\project.py", line 47, in __init__
    self.name = self.path.split('/')[-1]
TypeError: 'NoneType' object is not callable

**Comment by subbaraocherukuri** [comment]
https://github.com/llooker/pylookml/blob/25f4b026944d0bf7dc932fdb4ce0d1a60f34403f/lookml/tests/scenarios/scenario_gen_from_schema_test.py#L69

**Comment by rahuljeyasingh** [comment]
Hi @subbaraocherukuri ,

lookml.File Function accepts string (path of the file) as argument instead of View object.

**Comment by russlooker** [comment]
The code for this would be:

```
view = lookml.View('test_n')
my_file = lookml.File('test_n.view.lkml')
my_file + view
```
